/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author Uzulu
 */
public class Aplicacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aplicacion.class.getName());

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Personalizadabutton = new javax.swing.JRadioButton();
        Personalizadatxt = new javax.swing.JTextField();
        Confirmarbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Horas a alquilar");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1 Hora / 1200$");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2 Horas / 2400");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        buttonGroup1.add(Personalizadabutton);
        Personalizadabutton.setText("Personalizada");
        Personalizadabutton.addActionListener(this::PersonalizadabuttonActionPerformed);

        Personalizadatxt.setEnabled(false);

        Confirmarbutton.setText("Confirmar");
        Confirmarbutton.addActionListener(this::ConfirmarbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Personalizadabutton)
                                .addGap(18, 18, 18)
                                .addComponent(Personalizadatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Confirmarbutton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Personalizadabutton)
                    .addComponent(Personalizadatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Confirmarbutton)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        Personalizadatxt.setEnabled(false);
        Personalizadatxt.setText(""); // Limpia lo que hayan escrito
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void ConfirmarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarbuttonActionPerformed
        int horasAlquilar = 0;
        int precio = 0;
        
        if (jRadioButton1.isSelected()) {
            horasAlquilar = 1;
            precio = 1200;
        } else if (jRadioButton2.isSelected()) {
            horasAlquilar = 2;
            precio = 2400;
        } else if (Personalizadabutton.isSelected()) {
            // Validamos que no dejen el campo vacío o pongan letras
            try {
                horasAlquilar = Integer.parseInt(Personalizadatxt.getText());
                precio = horasAlquilar * 1200; // Calculamos el precio base por hora
                
                if (horasAlquilar <= 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresá una cantidad mayor a 0.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingresá un número válido de horas.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar una opción de tiempo.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Mensaje de confirmación final usando JOptionPane de Swing
        javax.swing.JOptionPane.showMessageDialog(this, "Alquiler confirmado por " + horasAlquilar + " hora(s).\nTotal a pagar: $" + precio);
        Menu menuCafeteria = new Menu(); // Recordá cambiar 'Menu' si tu archivo se llama distinto
        menuCafeteria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ConfirmarbuttonActionPerformed

    private void PersonalizadabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalizadabuttonActionPerformed
        Personalizadatxt.setEnabled(true);
        Personalizadatxt.requestFocus(); // Hace parpadear el cursor ahí
    }//GEN-LAST:event_PersonalizadabuttonActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        Personalizadatxt.setEnabled(false);
        Personalizadatxt.setText(""); // Limpia lo que hayan escrito
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aplicacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmarbutton;
    private javax.swing.JRadioButton Personalizadabutton;
    private javax.swing.JTextField Personalizadatxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
