/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author Uzulu
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Cafeconmedialunas = new javax.swing.JRadioButton();
        Cafenegrosolo = new javax.swing.JRadioButton();
        gaseosaconsnack = new javax.swing.JRadioButton();
        snackaseleccion = new javax.swing.JRadioButton();
        gaseosa = new javax.swing.JRadioButton();
        promo2cafesconmedialunapromo = new javax.swing.JRadioButton();
        sanwichjamonyqueso = new javax.swing.JRadioButton();
        confirmarpedido = new javax.swing.JButton();
        saltarmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        Cafeconmedialunas.setText("Cafe con medialunas");
        Cafeconmedialunas.addActionListener(this::CafeconmedialunasActionPerformed);

        Cafenegrosolo.setText("Cafe Negro");
        Cafenegrosolo.addActionListener(this::CafenegrosoloActionPerformed);

        gaseosaconsnack.setText("Gaseosa con snack");
        gaseosaconsnack.addActionListener(this::gaseosaconsnackActionPerformed);

        snackaseleccion.setText("Snack a seleccion");
        snackaseleccion.addActionListener(this::snackaseleccionActionPerformed);

        gaseosa.setText("Gaseosa");
        gaseosa.addActionListener(this::gaseosaActionPerformed);

        promo2cafesconmedialunapromo.setText("Promo 2 Cafes con Medialunas");
        promo2cafesconmedialunapromo.addActionListener(this::promo2cafesconmedialunapromoActionPerformed);

        sanwichjamonyqueso.setText("3 Sandwich de jamon y queso");
        sanwichjamonyqueso.addActionListener(this::sanwichjamonyquesoActionPerformed);

        confirmarpedido.setText("Confirmar pedido");
        confirmarpedido.setEnabled(false);
        confirmarpedido.addActionListener(this::confirmarpedidoActionPerformed);

        saltarmenu.setText("Saltar");
        saltarmenu.addActionListener(this::saltarmenuActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Cafenegrosolo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gaseosaconsnack, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snackaseleccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gaseosa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(sanwichjamonyqueso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmarpedido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saltarmenu, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(Cafeconmedialunas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promo2cafesconmedialunapromo)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cafeconmedialunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cafenegrosolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaseosaconsnack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snackaseleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaseosa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promo2cafesconmedialunapromo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sanwichjamonyqueso)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saltarmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmarpedido)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CafeconmedialunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafeconmedialunasActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_CafeconmedialunasActionPerformed

    private void CafenegrosoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafenegrosoloActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_CafenegrosoloActionPerformed

    private void confirmarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarpedidoActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Abriendo sesión en la computadora...");
        Pantallausuario pc = new Pantallausuario(); // El nombre de tu nueva pantalla
        pc.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_confirmarpedidoActionPerformed

    private void gaseosaconsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaconsnackActionPerformed
       confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_gaseosaconsnackActionPerformed

    private void snackaseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackaseleccionActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_snackaseleccionActionPerformed

    private void gaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_gaseosaActionPerformed

    private void promo2cafesconmedialunapromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promo2cafesconmedialunapromoActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_promo2cafesconmedialunapromoActionPerformed

    private void sanwichjamonyquesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanwichjamonyquesoActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_sanwichjamonyquesoActionPerformed

    private void saltarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltarmenuActionPerformed
       
        javax.swing.JOptionPane.showMessageDialog(this, "Abriendo sesión en la computadora...");
        Pantallausuario pc = new Pantallausuario(); // El nombre de tu nueva pantalla
        pc.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_saltarmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cafeconmedialunas;
    private javax.swing.JRadioButton Cafenegrosolo;
    private javax.swing.JButton confirmarpedido;
    private javax.swing.JRadioButton gaseosa;
    private javax.swing.JRadioButton gaseosaconsnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton promo2cafesconmedialunapromo;
    private javax.swing.JButton saltarmenu;
    private javax.swing.JRadioButton sanwichjamonyqueso;
    private javax.swing.JRadioButton snackaseleccion;
    // End of variables declaration//GEN-END:variables
}
