package cibercafe.vista;

import cibercafe.controllers.SesionController;
import cibercafe.dao.CategoriaDAO;
import cibercafe.modelo.Categoria;
import cibercafe.modelo.Computadora;
import cibercafe.dao.ComputadoraDAO;
import java.util.List;
/**
 *
 * @author Uzulu
 */
public class Aplicacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Aplicacion.class.getName());

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        SesionController sc = new SesionController();
        sc.liberarSesionesVencidas();
        cargarPCs();
    }
    public void cargarPCs() {
        ComputadoraDAO dao = new ComputadoraDAO();
    List<Computadora> lista = dao.obtenerTodos();
    for (Computadora c : lista) {
        comboPCs.addItem(c.getNombre());
        switch (c.getId()) {
            case 1: jLabel7.setText("PC-01 - Estado: " + c.getEstado()); break;
            case 2: jLabel9.setText("PC-02 - Estado: " + c.getEstado()); break;
            case 3: jLabel8.setText("PC-03 - Estado: " + c.getEstado()); break;
            case 4: jLabel10.setText("PC-04 - Estado: " + c.getEstado()); break;
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        Confirmarbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboPCs = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Elegí tu PC");

        Confirmarbutton.setBackground(new java.awt.Color(0, 153, 153));
        Confirmarbutton.setText("Confirmar");
        Confirmarbutton.addActionListener(this::ConfirmarbuttonActionPerformed);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccionar PC:");

        comboPCs.setEditable(true);
        comboPCs.addActionListener(this::comboPCsActionPerformed);

        jLabel3.setText("PC GAMER $2000/h ");

        jLabel4.setText("PC ESTÁNDAR $1000/h");

        jLabel5.setText("GAMER");

        jLabel6.setText("ESTÁNDAR");

        jLabel7.setText("PC-01 - Estado:");

        jLabel8.setText("PC-03 - Estado:");

        jLabel9.setText("PC-02 - Estado:");

        jLabel10.setText("PC-04 - Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Confirmarbutton)
                .addGap(127, 127, 127))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboPCs, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(112, 112, 112))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPCs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Confirmarbutton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarbuttonActionPerformed
    String pcSeleccionada = (String) comboPCs.getSelectedItem();
    
    if (pcSeleccionada == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Seleccioná una PC.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    ComputadoraDAO compDao = new ComputadoraDAO();
    CategoriaDAO catDao = new CategoriaDAO();
    List<Computadora> lista = compDao.obtenerTodos();

    int precioPorHora = 1000;
    int idPCSeleccionada = 1;
   for (Computadora c : lista) {
    if (c.getNombre().equals(pcSeleccionada)) {
        if ("activa".equals(c.getEstado())) {
            javax.swing.JOptionPane.showMessageDialog(this, "La PC " + pcSeleccionada + " está ocupada. Elegí otra.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if ("mantenimiento".equals(c.getEstado())) {
            javax.swing.JOptionPane.showMessageDialog(this, "La PC " + pcSeleccionada + " está en mantenimiento.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Categoria cat = catDao.buscarPorId(c.getIdCategoria());
        precioPorHora = (int) cat.getPrecioHora();
        idPCSeleccionada = c.getId();
        break;
    }
}

    int horasAlquilar;
    try {
       String input = javax.swing.JOptionPane.showInputDialog(this, "¿Cuántas horas desea alquilar?");
if (input == null) return;
horasAlquilar = Integer.parseInt(input.trim());
        if (horasAlquilar <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresá una cantidad mayor a 0.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresá un número válido de horas.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    int precio = horasAlquilar * precioPorHora;

    SesionController controller = new SesionController();
    int idSesion = controller.iniciarSesion(1, idPCSeleccionada, horasAlquilar, precio);

    javax.swing.JOptionPane.showMessageDialog(this, "Alquiler confirmado por " + horasAlquilar + " hora(s).\nTotal: $" + precio);
    Menu menuCafeteria = new Menu(horasAlquilar, pcSeleccionada, idSesion);
    menuCafeteria.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ConfirmarbuttonActionPerformed

    private void comboPCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPCsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPCsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Aplicacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmarbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboPCs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
