package cibercafe.vista;

import cibercafe.controllers.PedidoController;

/**
 *
 * @author Uzulu
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private int horasAlquiladas;
    private String nombrePC;
    private int idSesion;
    
    public Menu(int horasAlquiladas, String nombrePC, int idSesion) {
        initComponents();
        this.horasAlquiladas = horasAlquiladas;
        this.nombrePC = nombrePC;
        this.idSesion = idSesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Cafeconmedialunas = new javax.swing.JRadioButton();
        Cafenegrosolo = new javax.swing.JRadioButton();
        gaseosaconsnack = new javax.swing.JRadioButton();
        snackaseleccion = new javax.swing.JRadioButton();
        gaseosa = new javax.swing.JRadioButton();
        promo2cafesconmedialunapromo = new javax.swing.JRadioButton();
        sanwichjamonyqueso = new javax.swing.JRadioButton();
        confirmarpedido = new javax.swing.JButton();
        saltarmenu = new javax.swing.JButton();
        listaPrecios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        Cafeconmedialunas.setText("Cafe con medialunas");
        Cafeconmedialunas.addActionListener(this::CafeconmedialunasActionPerformed);

        Cafenegrosolo.setText("Cafe Negro");
        Cafenegrosolo.addActionListener(this::CafenegrosoloActionPerformed);

        gaseosaconsnack.setText("Gaseosa con snack");
        gaseosaconsnack.addActionListener(this::gaseosaconsnackActionPerformed);

        snackaseleccion.setText("Snack a seleccion");
        snackaseleccion.addActionListener(this::snackaseleccionActionPerformed);

        gaseosa.setText("Gaseosa");
        gaseosa.addActionListener(this::gaseosaActionPerformed);

        promo2cafesconmedialunapromo.setText("Promo 2 Cafes con Medialunas");
        promo2cafesconmedialunapromo.addActionListener(this::promo2cafesconmedialunapromoActionPerformed);

        sanwichjamonyqueso.setText("3 Sandwich de jamon y queso");
        sanwichjamonyqueso.addActionListener(this::sanwichjamonyquesoActionPerformed);

        confirmarpedido.setText("Confirmar pedido");
        confirmarpedido.setEnabled(false);
        confirmarpedido.addActionListener(this::confirmarpedidoActionPerformed);

        saltarmenu.setText("Saltar");
        saltarmenu.addActionListener(this::saltarmenuActionPerformed);

        listaPrecios.setText("Lista de Precios");
        listaPrecios.addActionListener(this::listaPreciosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sanwichjamonyqueso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(listaPrecios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmarpedido, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saltarmenu, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cafenegrosolo)
                            .addComponent(gaseosaconsnack)
                            .addComponent(snackaseleccion)
                            .addComponent(gaseosa)
                            .addComponent(Cafeconmedialunas)
                            .addComponent(promo2cafesconmedialunapromo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cafeconmedialunas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cafenegrosolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaseosaconsnack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snackaseleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gaseosa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promo2cafesconmedialunapromo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sanwichjamonyqueso)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saltarmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarpedido)
                    .addComponent(listaPrecios))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CafeconmedialunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafeconmedialunasActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_CafeconmedialunasActionPerformed

    private void CafenegrosoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CafenegrosoloActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_CafenegrosoloActionPerformed

    private void confirmarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarpedidoActionPerformed
           int idProducto = 0;
    double precio = 0;

    if (Cafeconmedialunas.isSelected()) { idProducto = 1; precio = 1000; }
    else if (Cafenegrosolo.isSelected()) { idProducto = 4; precio = 1000; }
    else if (gaseosaconsnack.isSelected()) { idProducto = 2; precio = 800; }
    else if (snackaseleccion.isSelected()) { idProducto = 3; precio = 1200; }
    else if (gaseosa.isSelected()) { idProducto = 2; precio = 800; }
    else if (promo2cafesconmedialunapromo.isSelected()) { idProducto = 1; precio = 1500; }
    else if (sanwichjamonyqueso.isSelected()) { idProducto = 3; precio = 1200; }

    PedidoController controller = new PedidoController();
    controller.registrarPedido(1, idSesion, idProducto, 1, precio);

    javax.swing.JOptionPane.showMessageDialog(this, "Pedido confirmado!");
    Pantallausuario pc = new Pantallausuario(nombrePC, "01:00:00", precio, horasAlquiladas);
    pc.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_confirmarpedidoActionPerformed

    private void gaseosaconsnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaconsnackActionPerformed
       confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_gaseosaconsnackActionPerformed

    private void snackaseleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snackaseleccionActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_snackaseleccionActionPerformed

    private void gaseosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaseosaActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_gaseosaActionPerformed

    private void promo2cafesconmedialunapromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promo2cafesconmedialunapromoActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_promo2cafesconmedialunapromoActionPerformed

    private void sanwichjamonyquesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanwichjamonyquesoActionPerformed
        confirmarpedido.setEnabled(true);
    }//GEN-LAST:event_sanwichjamonyquesoActionPerformed

    private void saltarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltarmenuActionPerformed
       
        javax.swing.JOptionPane.showMessageDialog(this, "Abriendo sesión en la computadora...");
        Pantallausuario pc = new Pantallausuario(nombrePC, "01:00:00",0, horasAlquiladas);
        pc.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_saltarmenuActionPerformed

    private void listaPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPreciosActionPerformed
        ListadoPrecios vent = new ListadoPrecios();
        vent.setVisible(true);
    }//GEN-LAST:event_listaPreciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu(1, "PC- 01", 1).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cafeconmedialunas;
    private javax.swing.JRadioButton Cafenegrosolo;
    private javax.swing.JButton confirmarpedido;
    private javax.swing.JRadioButton gaseosa;
    private javax.swing.JRadioButton gaseosaconsnack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listaPrecios;
    private javax.swing.JRadioButton promo2cafesconmedialunapromo;
    private javax.swing.JButton saltarmenu;
    private javax.swing.JRadioButton sanwichjamonyqueso;
    private javax.swing.JRadioButton snackaseleccion;
    // End of variables declaration//GEN-END:variables
}
